name: mawaheb_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  core_sdk: 
    git:   
     url: https://gitlab.com/abd.ktefane.7/flutter-core.git 
     ref: master

  # DATA
  shared_preferences:  ^2.0.5
  supercharged: ^2.0.0
  tuple: ^2.0.0
  device_info: ^2.0.0
  package_info: ^2.0.0
  mime: ^1.0.0

  # Firebase
  firebase_core: ^1.1.0
  firebase_messaging: ^10.0.0

  # Networking
  # dio_flutter_transformer: ^3.0.2
  # dio_cookie_manager: ^1.0.0

  # State Managment
  provider: ^5.0.0

  # UI
  webview_flutter: ^2.0.4
  animations: ^2.0.0
  pin_code_text_field: ^1.8.0
  flutter_local_notifications: ^5.0.0+4
  fancy_shimmer_image: ^2.0.0-nullsafety.0
  cupertino_icons: ^1.0.3
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  # easy_gradient_text: any
  dotted_decoration: ^2.0.0
  modal_bottom_sheet: ^2.0.0
  url_launcher: ^6.0.3
  image_picker:  ^0.7.4
  google_maps_flutter: ^2.0.3
  cached_network_image: ^3.0.0-nullsafety

  # full_screen_image: any 
  # downloads_path_provider: any
  path_provider: ^2.0.1
  permission_handler: ^7.1.0
  # video_player: ^1.0.1
  open_file: ^3.2.1 
  video_player: ^2.1.1
  chewie: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.2
  mockito: ^5.0.7
  mobx_codegen: ^2.0.1+3
  built_value_generator: ^8.0.6
  json_serializable: ^4.1.1
  injectable_generator: ^1.4.0
  flutter_launcher_icons: ^0.9.0
  # pedantic: ^1.9.2

  
flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/ic_launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - lang/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic


    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Black.ttf
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
        - asset: assets/fonts/cairo/Cairo-Light.ttf
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf

